### ISSUE TITLE
Add LSF batch scripts

### ISSUE THREAD

**Issue by al-rigazzi** [CrayLabs/SmartSim-Scaling#11]
When running on LSF-based systems, such as Summit, one has to specify how many GPUs and CPUs each RS needs to be accessing. This is reflected in `LSFSettings`, but for the simple scaling applications, it could be enough to add it to the batch scripts or as `batch_args`. This should be investigated, to allow users to run the scaling tests without changing the driver script.

**Comment by mellis13** [comment]
Closing as LSF support is not planned for the SmartSim-Scaling repo.
