### ISSUE TITLE
Validate multi-GPU support functions with colocated inference

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartSim-Scaling#14]
**Summary**
Multi-GPU support functions in Redis need to be tested for inference models using both the colocated database and tweaked as necessary to work there.

**Acceptance criteria:**
- [ ] Update driver to use multiGPU functions with colocated inference
- [ ] Verify correct function on pearl mutter

**Comment by mellis13** [comment]
The scaling study has the ability to launch the colocated inference on multiple GPUs and the WLM tests also test the backends with a ``add_ml_model()`` call that is parameterized to run on multiple GPUs.  The nightly tests will run this on multiple GPUs.
