### ISSUE TITLE
No response to ^C during Scaling test run

### ISSUE THREAD

**Issue by amandarichardsonn** [CrayLabs/SmartSim-Scaling#41]
## Description
If you would like to end a scaling test during a run, you must run `scancel -u $USER` or `scancel #JOBID` in a separate terminal to your allocation. This is because the terminal does not respond to ^C. This means that the scaling test is not responding to the cancel funcs in SmartSim. 

## How to Reproduce
Setup your env to run a scaling test, do not submit a batch script but instead launch within terminal via `python driver.py <test>`.  Once your scaling test has indicated that its running within the terminal, run `control C`. You will see that it is ignored.

**Comment by mellis13** [comment]
@amandarichardsonn Let's promote this to a general bug report to address
